name: Publish 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dontnet-version: '8.0.x'
  
    - name: Restore 
      run: dotnet restore ./Todos.WepAPI.sln
  
    - name: Build
      run: dotnet build ./Todos.WepAPI.sln --configuration Release
  
    - name: Publish
      run: dotnet publish ./Todos.WepAPI.sln --configuration Release --no-build
